# Generated by Django 4.1.3 on 2022-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0002_post_image3_post_p1_post_p2_post_p3_post_sh1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('image3', models.ImageField(default='', upload_to='images')),
                ('image4', models.ImageField(upload_to='images')),
                ('image5', models.ImageField(upload_to='images')),
                ('title1', models.CharField(default='', max_length=500)),
                ('title2', models.CharField(default='', max_length=500)),
                ('title3', models.CharField(default='', max_length=500)),
                ('title4', models.CharField(default='', max_length=500)),
                ('title5', models.CharField(default='', max_length=500)),
                ('p1', models.CharField(default='', max_length=400)),
                ('p2', models.CharField(default='', max_length=400)),
                ('p3', models.CharField(default='', max_length=400)),
                ('h1', models.CharField(default='', max_length=200)),
                ('h2', models.CharField(default='', max_length=200)),
                ('h3', models.CharField(default='', max_length=200)),
                ('h4', models.CharField(default='', max_length=200)),
                ('h5', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
