# Generated by Django 4.1.3 on 2022-11-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0004_posts_p4_posts_p5'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images')),
                ('image2', models.ImageField(upload_to='images')),
                ('h1', models.CharField(default='', max_length=500)),
                ('h2', models.CharField(default='', max_length=500)),
                ('p1', models.CharField(default='', max_length=200)),
                ('p2', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
