# Generated by Django 4.1.3 on 2022-11-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jj', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='p3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='p4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='p1',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='event',
            name='p2',
            field=models.CharField(default='', max_length=400),
        ),
    ]
